# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0017_userstory_generated_from_task'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['project', 'status'], name='userstories_project_c6fa7d_idx'),
        ),
    ]
